# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculadora.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'calculadora.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lculadora.proto\x12\x0b\x63\x61lculadora\"3\n\x0fOperacaoRequest\x12\x0f\n\x07numero1\x18\x01 \x01(\x01\x12\x0f\n\x07numero2\x18\x02 \x01(\x01\"&\n\x11ResultadoResponse\x12\x11\n\tresultado\x18\x01 \x01(\x01\x32\xa2\x01\n\x0b\x43\x61lculadora\x12\x46\n\x04Soma\x12\x1c.calculadora.OperacaoRequest\x1a\x1e.calculadora.ResultadoResponse\"\x00\x12K\n\tSubtracao\x12\x1c.calculadora.OperacaoRequest\x1a\x1e.calculadora.ResultadoResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculadora_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERACAOREQUEST']._serialized_start=34
  _globals['_OPERACAOREQUEST']._serialized_end=85
  _globals['_RESULTADORESPONSE']._serialized_start=87
  _globals['_RESULTADORESPONSE']._serialized_end=125
  _globals['_CALCULADORA']._serialized_start=128
  _globals['_CALCULADORA']._serialized_end=290
# @@protoc_insertion_point(module_scope)
